[package]
name = "csr"
version = "0.1.0"
authors = ["Remy Wang <remy.sucre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.6.0"
env_logger = "0.7"
